jobs:
  compile:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      uses: actions/cache@v1
      with:
        key: ${{ matrix.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ matrix.os }}-maven-

          '
    - continue-on-error: true
      name: Build with maven
      run: mvn --no-transfer-progress verify
    strategy:
      matrix:
        java:
        - '21'
        os:
        - ubuntu-latest
        - ubuntu-20.04
        - windows-latest
        - macos-latest
name: build
on:
  repository_dispatch:
    types: trigger-ga___master-build.yml
